myshop/myshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls', namespace='shop')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

myshop/shop/urls.py
from django.urls import path

from . import views

app_name = 'shop'

urlpatterns = [
    path('', views.product_list, name='product_list'),
    path('<slug:category_slug>/', views.product_list, name='product_list_by_category'),
    path('brand/<slug:brand_slug>/', views.product_list, name='product_list_by_brand'), 
    path('<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),
]


myshop/shop/models.py
from django.db import models
from django.urls import reverse

class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

class Brand(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200,
                            unique=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['name']),
        ]
        verbose_name = 'brand'
        verbose_name_plural = 'brands'

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('shop:product_list_by_brand',
                       args=[self.slug])

class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,
                                 related_name='products',
                                 on_delete=models.CASCADE)                             
    name = models.CharField(max_length=200)
    slug = models.SlugField(max_length=200)
    image = models.ImageField(upload_to='products/%Y/%m/%d',
                              blank=True)
    description = models.TextField(blank=True)
    price = models.DecimalField(max_digits=10,
                                decimal_places=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['name']
        indexes = [
            models.Index(fields=['id', 'slug']),
            models.Index(fields=['name']),
            models.Index(fields=['-created']),
        ]

    def __str__(self):
        return self.name
        
    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

myshop/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product, Brand

def product_list(request, category_slug=None, brand_slug=None):
    category = None
    brand = None
    categories = Category.objects.all()
    brands = Brand.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    if brand_slug:
        brand = get_object_or_404(Brand, slug=brand_slug)
        products = products.filter(brand=brand)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'brand': brand,  # Add 'brand' to context
                   'brands': brands,  # Add 'brands' to context
                   'products': products})


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)

    return render(request,
                  'shop/product/detail.html',
                  {'product': product})


myshop/shop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>{% block title %}Магазин электроники{% endblock %}</title>
    <link href="{% static "css/base.css" %}" rel="stylesheet">
  </head>
  <body>
    <div id="header">
      <a href="/" class="logo">Магазин электроники</a>
    </div>
    <div id="subheader">
      <div class="cart">
        Корзина
      </div>
    </div>
    <div id="content">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

myshop/shop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {{ product.name }}
{% endblock %}

{% block content %}
  <div class="product-detail">
    <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="Product Image">
    <h1>{{ product.name }}</h1>
    <h2>
      <a href="{{ product.category.get_absolute_url }}">
        {{ product.category }}
      </a>
    </h2>
    <p class="price">{{ product.price }} ₽</p>
    {{ product.description|linebreaks }}
  </div>
{% endblock %}

myshop/shop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  {% if category %}{{ category.name }} | Магазин электроники{% else %}Каталог | Магазин Электроники{% endif %}
{% endblock %}

{% block content %}
  <div id="sidebar">
  
    <h3>Категории</h3>
    <ul>
      <li {% if not category %}class="selected"{% endif %}>
        <a href="{% url 'shop:product_list' %}">Все товары</a>
      </li>
      {% for c in categories %}
        <li {% if category and category.slug == c.slug %}class="selected"{% endif %}>
          <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
        </li>
      {% endfor %}
    </ul>
    
    <h3>Бренды</h3>
    <ul>
      <li {% if not brand %}class="selected"{% endif %}>
        <a href="{% url 'shop:product_list' %}">Все товары</a>
      </li>
      {% for b in brands %}
        <li {% if brand and brand.slug == b.slug %}class="selected"{% endif %}>
          <a href="{{ b.get_absolute_url }}">{{ b.name }}</b> </a>
         
        </li>
      {% endfor %}
    </ul>
    
  </div>
  <div id="main" class="product-list">
    <h1>{% if category %}{{ category.name }}{% else %}Каталог{% endif %}</h1>
    {% for product in products %}
      <div class="item">
        <a href="{{ product.get_absolute_url }}">
          <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}" alt="{{ product.name }}">
        </a>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
        <br>
        {{ product.price }} ₽
      </div>
    {% endfor %}
  </div>
{% endblock %}
